services:
  e2e:
    container_name: e2e
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo

  reservations:
    container_name: reservations_e2e
    image: us-east4-docker.pkg.dev/sleepr-386921/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'

  auth:
    container_name: auth_e2e
    image: us-east4-docker.pkg.dev/sleepr-386921/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'

  payments:
    container_name: payments_e2e
    image: us-east4-docker.pkg.dev/sleepr-386921/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    container_name: notifications_e2e
    image: us-east4-docker.pkg.dev/sleepr-386921/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'

  mongo:
    container_name: mongo_e2e
    image: mongo
    restart: always
    ports:
      - "27017:27017"
